# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

score_blackjackC <- function(x, y = as.integer( c(0))) {
    .Call(`_gambleR_score_blackjackC`, x, y)
}

simulate_blackjackC <- function(n_players, n_hands, card_deck) {
    .Call(`_gambleR_simulate_blackjackC`, n_players, n_hands, card_deck)
}

