# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simulate_blackjack <- function(n_decks, n_players, n_hands, card_deck) {
    .Call(`_gambleR_simulate_blackjack`, n_decks, n_players, n_hands, card_deck)
}

